version: "3.9"

services:
  shepherd-app:
    image: mazzolino/shepherd
    env_file : ${HOME}/traefik/shepherd/config/shepherd.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints: [node.role == manager]

