[global]
  checkNewVersion = true
  sendAnonymousUsage = false

#[pilot]
#  token = ""

[log]
  level = "INFO"

[api]
  insecure = false
  dashboard = true
  debug = true

[entryPoints]
  [entrypoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
      certResolver = "letsencrypt"

[providers]
  [providers.docker]
    swarmMode = true
    watch = true
    exposedByDefault = false
    network = "traefik-network"

[certificatesResolvers]
  [certificatesResolvers.letsencrypt]
    [certificatesResolvers.letsencrypt.acme]
      email = "E-MAIL"
      storage = "/letsencrypt/acme.json"
      # Staging CA for testing purposes; uncomment to test your configuration and avoid being rate-limited
      #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

    [certificatesResolvers.letsencrypt.acme.dnsChallenge]
      provider = "cloudflare"
      delayBeforeCheck = 0
      # Often internal DNS resolers will cache txt records for longer than the LEGO challenge takes. Specify external providers here to validate the records.
      resolvers = ["1.1.1.1:53", "8.8.8.8:53"]


[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]
    addEntryPointsLabels = true
    addServicesLabels = true
